 services:
  pkmn-database:
     image: postgres
     restart: "no"
     ports:
       - "5433:5432"
     volumes:
       - pkmn-database_data:/var/lib/postgresql/data
     environment:
       POSTGRES_USER: pkmn_user
       POSTGRES_PASSWORD: pkmn_password
       POSTGRES_DB: pkmn_db
     networks:
       - pkmn-net
  pkmn-app-Pegov:
    image: pkmn-tag
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - pkmn-db-migration:/db/migration
    environment:
      DATABASE_URL: pkmn-database
    networks:
      - pkmn-net

volumes:
  pkmn-database_data:
  pkmn-db-migration:
networks:
  pkmn-net: